[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "torch_int"
dynamic = ["version"]
description = "PyTorch INT8 quantization with CUTLASS"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "torch",
    "transformers",
    "datasets",
    "accelerate",
    "icecream",
]

[tool.setuptools_scm]